#!/usr/bin/env node

/**
 * Deterministic Scene Compositor
 * ==============================
 * Core engine of the Stickman Animation Agent pipeline.
 *
 * Reads a Scene Definition JSON (structured data generated by the LLM) and
 * produces a complete HTML document with embedded SVGs and a GSAP timeline
 * that HyperFrames renders to video via headless Chrome.
 *
 * Usage:
 *   node src/compositor/index.js \
 *     --scene compositions/scene-01.json \
 *     --project projects/my-video/ \
 *     --template whiteboard \
 *     --output compositions/scene-01.html
 */

import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { generateAnimation, supportedActions } from './animations.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const REPO_ROOT = path.resolve(import.meta.dirname, '..', '..');
const COMPONENTS_DIR = path.join(REPO_ROOT, 'components', 'characters');
const TEMPLATES_DIR = path.join(REPO_ROOT, 'templates');

// Component categories that map to character sheet fields
const COMPONENT_CATEGORIES = {
  head: { dir: 'heads', partName: 'head' },
  torso: { dir: 'torsos', partName: 'torso' },
  hair: { dir: 'hair', partName: 'hair' },
  defaultExpression: { dir: 'expressions', partName: 'expression' },
  defaultArms: { dir: 'arms', partName: 'arm_right' },
  defaultLegs: { dir: 'legs', partName: 'legs' },
};

// Attachment point pairing — which parent point connects to which child point
const ATTACHMENT_CHAIN = [
  { parent: 'head', parentPoint: 'neck', child: 'torso', childPoint: 'neck' },
  { parent: 'torso', parentPoint: 'right-shoulder', child: 'arm_right', childPoint: 'shoulder' },
  { parent: 'torso', parentPoint: 'left-shoulder', child: 'arm_left', childPoint: 'shoulder' },
  { parent: 'torso', parentPoint: 'right-hip', child: 'legs', childPoint: 'hip' },
  { parent: 'head', parentPoint: 'hair-top', child: 'hair', childPoint: 'head-top' },
  { parent: 'head', parentPoint: 'face-center', child: 'expression', childPoint: 'face-center' },
  { parent: 'head', parentPoint: 'face-center', child: 'accessory_glasses', childPoint: 'face-center' },
  { parent: 'arm_right', parentPoint: 'wrist', child: 'hand_right', childPoint: 'wrist' },
  { parent: 'arm_left', parentPoint: 'wrist', child: 'hand_left', childPoint: 'wrist' },
  { parent: 'legs', parentPoint: 'right-ankle', child: 'foot_right', childPoint: 'ankle' },
  { parent: 'legs', parentPoint: 'left-ankle', child: 'foot_left', childPoint: 'ankle' },
];

// ---------------------------------------------------------------------------
// File I/O helpers
// ---------------------------------------------------------------------------

function readJSON(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`File not found: ${filePath}`);
  }
  const raw = fs.readFileSync(filePath, 'utf-8');
  try {
    return JSON.parse(raw);
  } catch (err) {
    throw new Error(`Invalid JSON in ${filePath}: ${err.message}`);
  }
}

function readSVG(filePath) {
  if (!fs.existsSync(filePath)) {
    return null; // Missing optional components are OK
  }
  return fs.readFileSync(filePath, 'utf-8');
}

// ---------------------------------------------------------------------------
// SVG Parsing
// ---------------------------------------------------------------------------

/**
 * Parse data-attach-* attributes from an SVG string.
 * Returns a map of  { pointName: { x, y } }.
 *
 * Example:  data-attach-neck="0,0"  →  { neck: { x: 0, y: 0 } }
 */
function parseAttachPoints(svgContent) {
  const points = {};
  const regex = /data-attach-([\w-]+)="([^"]+)"/g;
  let match;
  while ((match = regex.exec(svgContent)) !== null) {
    const name = match[1];
    const [xStr, yStr] = match[2].split(',');
    points[name] = { x: parseFloat(xStr), y: parseFloat(yStr) };
  }
  return points;
}

/**
 * Extract the inner content of an SVG's root <g> element, stripping the
 * outer <svg> wrapper so we can embed it inside a parent <g>.
 */
function extractSVGContent(svgContent) {
  // Strip XML declaration if present
  let s = svgContent.replace(/<\?xml[^?]*\?>\s*/g, '');
  // Strip comments at the top level (outside the <g>)
  s = s.replace(/<!--[\s\S]*?-->/g, '');
  // Extract everything between <svg ...> and </svg>
  const svgMatch = s.match(/<svg[^>]*>([\s\S]*)<\/svg>/i);
  if (!svgMatch) return s.trim();
  return svgMatch[1].trim();
}

/**
 * Extract the viewBox from an SVG string.
 * Returns { minX, minY, width, height } or null.
 */
function parseViewBox(svgContent) {
  const match = svgContent.match(/viewBox="([^"]+)"/);
  if (!match) return null;
  const parts = match[1].split(/\s+/).map(Number);
  if (parts.length !== 4) return null;
  return { minX: parts[0], minY: parts[1], width: parts[2], height: parts[3] };
}

// ---------------------------------------------------------------------------
// Template Loading
// ---------------------------------------------------------------------------

/**
 * Load and merge template config.
 * If the template extends _base, merge base defaults underneath.
 */
function loadTemplate(templateName) {
  const templatePath = path.join(TEMPLATES_DIR, templateName, 'template.json');
  const template = readJSON(templatePath);

  if (template.extends) {
    const basePath = path.join(TEMPLATES_DIR, template.extends, 'template.json');
    if (fs.existsSync(basePath)) {
      const base = readJSON(basePath);
      // Deep-merge: template overrides base
      return deepMerge(base, template);
    }
  }

  return template;
}

/**
 * Simple two-level deep merge. Target values take precedence.
 */
function deepMerge(base, override) {
  const result = { ...base };
  for (const key of Object.keys(override)) {
    if (
      override[key] &&
      typeof override[key] === 'object' &&
      !Array.isArray(override[key]) &&
      base[key] &&
      typeof base[key] === 'object' &&
      !Array.isArray(base[key])
    ) {
      result[key] = { ...base[key], ...override[key] };
    } else {
      result[key] = override[key];
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Character Assembly
// ---------------------------------------------------------------------------

/**
 * Resolve the filesystem path for a character component SVG.
 *
 * @param {number} tier        - Character tier (1 or 2)
 * @param {string} category    - Directory name (heads, torsos, arms, etc.)
 * @param {string} variant     - File stem (e.g., "front", "tshirt", "relaxed")
 * @returns {string|null}       Absolute path, or null if not found
 */
function resolveComponentPath(tier, category, variant) {
  // Try the character's tier first, then fall back to tier1
  const tiersToTry = tier === 2 ? ['tier2', 'tier1'] : ['tier1'];
  for (const t of tiersToTry) {
    const p = path.join(COMPONENTS_DIR, t, category, `${variant}.svg`);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

/**
 * Resolve the path for an accessory SVG.
 */
function resolveAccessoryPath(variant) {
  const p = path.join(COMPONENTS_DIR, 'tier2', 'accessories', `${variant}.svg`);
  if (fs.existsSync(p)) return p;
  return null;
}

/**
 * Resolve the path for a prop SVG.
 */
function resolvePropPath(propId) {
  const p = path.join(COMPONENTS_DIR, 'props', `${propId}.svg`);
  if (fs.existsSync(p)) return p;
  return null;
}

/**
 * Load all expression SVGs for a character (so we can embed them all and
 * toggle visibility for expression-change animations).
 */
function loadAllExpressions(tier) {
  const expressions = {};
  const tiersToTry = tier === 2 ? ['tier2', 'tier1'] : ['tier1'];
  for (const t of tiersToTry) {
    const dir = path.join(COMPONENTS_DIR, t, 'expressions');
    if (fs.existsSync(dir)) {
      for (const file of fs.readdirSync(dir)) {
        if (file.endsWith('.svg')) {
          const name = path.basename(file, '.svg');
          if (!expressions[name]) {
            expressions[name] = fs.readFileSync(path.join(dir, file), 'utf-8');
          }
        }
      }
    }
  }
  return expressions;
}

/**
 * Assemble a complete character SVG group from its character sheet.
 *
 * The assembly process:
 * 1. Load each component SVG referenced by the character sheet
 * 2. Parse attachment points from each component
 * 3. Position child components relative to parents using attachment point math
 * 4. Wrap everything in a <g> with the character's position from the scene def
 *
 * @param {object} charSheet    - Character sheet JSON
 * @param {object} scenePlacement - Character placement from scene definition
 * @param {object} template     - Merged template config
 * @returns {string}            SVG markup for the complete character
 */
function assembleCharacter(charSheet, scenePlacement, template) {
  const tier = charSheet.tier || 1;
  const components = charSheet.components;
  const proportions = charSheet.proportions || {};
  const totalHeight = proportions.totalHeight || 220;

  // Determine the active pose
  const poseName = scenePlacement.pose || 'standing';
  const pose = (charSheet.poses && charSheet.poses[poseName]) || {};

  // Resolve which variant to use for each component slot, with pose overrides
  const slots = {
    head: components.head || 'front',
    torso: components.torso || 'tshirt',
    hair: components.hair || null,
    expression: pose.expression || components.defaultExpression || 'neutral',
    arm_right: pose.arms || components.defaultArms || 'relaxed',
    arm_left: pose.arms || components.defaultArms || 'relaxed',
    legs: pose.legs || components.defaultLegs || 'standing',
    hand_right: components.defaultHands || 'mitten-open',
    hand_left: components.defaultHands || 'mitten-open',
    foot_right: components.defaultFeet || 'standing-shoe',
    foot_left: components.defaultFeet || 'standing-shoe',
  };

  // Load SVGs and parse attach points
  const loaded = {};
  const attachPoints = {};

  // Head
  loaded.head = loadAndParse('head', 'heads', slots.head, tier);
  // Torso
  loaded.torso = loadAndParse('torso', 'torsos', slots.torso, tier);
  // Hair
  if (slots.hair && slots.hair !== 'bald') {
    loaded.hair = loadAndParse('hair', 'hair', slots.hair, tier);
  }
  // Arms
  loaded.arm_right = loadAndParse('arm_right', 'arms', slots.arm_right, tier);
  loaded.arm_left = loadAndParse('arm_left', 'arms', slots.arm_left, tier);
  // Legs
  loaded.legs = loadAndParse('legs', 'legs', slots.legs, tier);
  // Hands
  loaded.hand_right = loadAndParse('hand_right', 'hands', slots.hand_right, tier);
  loaded.hand_left = loadAndParse('hand_left', 'hands', slots.hand_left, tier);
  // Feet
  loaded.foot_right = loadAndParse('foot_right', 'feet', slots.foot_right, tier);
  loaded.foot_left = loadAndParse('foot_left', 'feet', slots.foot_left, tier);

  // Load all expressions for swap animations
  const allExpressions = loadAllExpressions(tier);

  // Compute positions using attachment chain
  // Start with head at top, torso attached below
  const positions = computePositions(loaded, proportions);

  // Build the SVG group
  const parts = [];
  const charX = scenePlacement.position?.x || 400;
  const charY = scenePlacement.position?.y || 400;
  const charScale = scenePlacement.scale || 1.0;

  // The character is assembled bottom-up for correct z-ordering:
  // feet -> legs -> torso -> arms -> hands -> head -> hair -> expression -> accessories
  const renderOrder = [
    'foot_left', 'foot_right',
    'legs',
    'torso',
    'arm_left', 'arm_right',
    'hand_left', 'hand_right',
    'head',
    'hair',
  ];

  for (const partName of renderOrder) {
    const comp = loaded[partName];
    if (!comp) continue;
    const pos = positions[partName] || { x: 0, y: 0 };
    parts.push(wrapPart(partName, comp.content, pos.x, pos.y));
  }

  // Expressions — embed all, show only the active one
  const activeExpression = slots.expression;
  for (const [exprName, exprSvg] of Object.entries(allExpressions)) {
    const pos = positions.expression || { x: 0, y: 0 };
    const display = exprName === activeExpression ? 'block' : 'none';
    parts.push(
      `  <g data-part="expression" data-expression="${exprName}" ` +
      `transform="translate(${pos.x}, ${pos.y})" style="display: ${display}">` +
      `\n    ${extractSVGContent(exprSvg)}\n  </g>`
    );
  }

  // Accessories (glasses, etc.)
  if (charSheet.distinguishing?.accessory) {
    const accPath = resolveAccessoryPath(charSheet.distinguishing.accessory);
    if (accPath) {
      const accSvg = readSVG(accPath);
      if (accSvg) {
        const accPoints = parseAttachPoints(accSvg);
        const pos = positions.expression || positions.head || { x: 0, y: 0 };
        parts.push(
          `  <g data-part="accessory" transform="translate(${pos.x}, ${pos.y})">` +
          `\n    ${extractSVGContent(accSvg)}\n  </g>`
        );
      }
    }
  }

  // Initial opacity: 0 (characters are revealed by timeline animations)
  return (
    `<g id="char-${charSheet.id}" ` +
    `transform="translate(${charX}, ${charY}) scale(${charScale})" ` +
    `opacity="0">\n` +
    parts.join('\n') +
    `\n</g>`
  );
}

/**
 * Load a component SVG and parse its attachment points.
 */
function loadAndParse(partName, category, variant, tier) {
  const filePath = resolveComponentPath(tier, category, variant);
  if (!filePath) return null;
  const raw = readSVG(filePath);
  if (!raw) return null;
  return {
    content: raw,
    attachPoints: parseAttachPoints(raw),
    viewBox: parseViewBox(raw),
  };
}

/**
 * Compute absolute positions for each part relative to the character origin.
 *
 * The assembly uses a top-down skeleton:
 *   head (origin: 0, 0 at neck)
 *   -> torso (neck attaches to head's neck point)
 *   -> arms (shoulders attach to torso's shoulder points)
 *   -> legs (hips attach to torso's hip points)
 *   -> hair (top attaches to head's hair-top point)
 *   -> expression (center attaches to head's face-center)
 *   -> hands (wrists attach to arm endpoints)
 *   -> feet (ankles attach to leg endpoints)
 *
 * @param {object} loaded       - Map of partName → { content, attachPoints, viewBox }
 * @param {object} proportions  - Character proportions from sheet
 * @returns {object}            Map of partName → { x, y }
 */
function computePositions(loaded, proportions) {
  const positions = {};
  const headDiameter = proportions.headDiameter || 80;

  // Head positioned so neck (0,0 in head-front coords) is at the character origin
  positions.head = { x: 0, y: 0 };

  // Torso: connect torso's neck point to head's neck point
  if (loaded.torso) {
    const torsoNeck = loaded.torso.attachPoints.neck || { x: 0, y: 0 };
    const headNeck = loaded.head?.attachPoints.neck || { x: 0, y: 0 };
    positions.torso = {
      x: headNeck.x - torsoNeck.x,
      y: headNeck.y - torsoNeck.y,
    };
  }

  // Arms: connect to torso shoulder points
  if (loaded.torso && loaded.arm_right) {
    const shoulderR = loaded.torso.attachPoints['right-shoulder'] || { x: 37, y: 7 };
    const armShoulder = loaded.arm_right.attachPoints.shoulder || { x: 0, y: 0 };
    positions.arm_right = {
      x: (positions.torso?.x || 0) + shoulderR.x - armShoulder.x,
      y: (positions.torso?.y || 0) + shoulderR.y - armShoulder.y,
    };
  }
  if (loaded.torso && loaded.arm_left) {
    const shoulderL = loaded.torso.attachPoints['left-shoulder'] || { x: -37, y: 7 };
    const armShoulder = loaded.arm_left.attachPoints.shoulder ||
                        loaded.arm_left.attachPoints['shoulder-left'] || { x: 0, y: 0 };
    positions.arm_left = {
      x: (positions.torso?.x || 0) + shoulderL.x - armShoulder.x,
      y: (positions.torso?.y || 0) + shoulderL.y - armShoulder.y,
    };
    // Mirror the left arm
    positions.arm_left.mirror = true;
  }

  // Legs: connect to torso hip point (use center between left and right hip)
  if (loaded.torso && loaded.legs) {
    const hipL = loaded.torso.attachPoints['left-hip'] || { x: -17, y: 63 };
    const hipR = loaded.torso.attachPoints['right-hip'] || { x: 17, y: 63 };
    const hipCenter = { x: (hipL.x + hipR.x) / 2, y: (hipL.y + hipR.y) / 2 };
    const legsHip = loaded.legs.attachPoints.hip || { x: 0, y: 0 };
    positions.legs = {
      x: (positions.torso?.x || 0) + hipCenter.x - legsHip.x,
      y: (positions.torso?.y || 0) + hipCenter.y - legsHip.y,
    };
  }

  // Hair: connect to head's hair-top point
  if (loaded.hair && loaded.head) {
    const hairTop = loaded.head.attachPoints['hair-top'] || { x: 0, y: -78 };
    const hairAttach = loaded.hair?.attachPoints['head-top'] || { x: 0, y: 0 };
    positions.hair = {
      x: (positions.head?.x || 0) + hairTop.x - hairAttach.x,
      y: (positions.head?.y || 0) + hairTop.y - hairAttach.y,
    };
  }

  // Expression: connect to head's face-center
  if (loaded.head) {
    // Face center is roughly at the middle of the head
    // For front.svg, the head origin is at neck (0,0), face is above
    const faceCenter = loaded.head.attachPoints['face-center'];
    if (faceCenter) {
      positions.expression = {
        x: (positions.head?.x || 0) + faceCenter.x,
        y: (positions.head?.y || 0) + faceCenter.y,
      };
    } else {
      // Estimate: face center is about 40% up the head from neck
      positions.expression = {
        x: (positions.head?.x || 0),
        y: (positions.head?.y || 0) - headDiameter * 0.5,
      };
    }
  }

  // Hands: connect to arm wrist points
  if (loaded.arm_right && loaded.hand_right) {
    const wrist = loaded.arm_right.attachPoints.wrist || { x: 24, y: 58 };
    const handWrist = loaded.hand_right.attachPoints.wrist || { x: 0, y: 0 };
    positions.hand_right = {
      x: (positions.arm_right?.x || 0) + wrist.x - handWrist.x,
      y: (positions.arm_right?.y || 0) + wrist.y - handWrist.y,
    };
  }
  if (loaded.arm_left && loaded.hand_left) {
    const wrist = loaded.arm_left.attachPoints.wrist || { x: 24, y: 58 };
    const handWrist = loaded.hand_left.attachPoints.wrist || { x: 0, y: 0 };
    positions.hand_left = {
      x: (positions.arm_left?.x || 0) + wrist.x - handWrist.x,
      y: (positions.arm_left?.y || 0) + wrist.y - handWrist.y,
    };
    positions.hand_left.mirror = true;
  }

  // Feet: connect to legs ankle points
  if (loaded.legs && loaded.foot_right) {
    const ankle = loaded.legs.attachPoints['right-ankle'] || { x: 18, y: 84 };
    const footAnkle = loaded.foot_right.attachPoints.ankle || { x: 0, y: 0 };
    positions.foot_right = {
      x: (positions.legs?.x || 0) + ankle.x - footAnkle.x,
      y: (positions.legs?.y || 0) + ankle.y - footAnkle.y,
    };
  }
  if (loaded.legs && loaded.foot_left) {
    const ankle = loaded.legs.attachPoints['left-ankle'] || { x: -18, y: 84 };
    const footAnkle = loaded.foot_left.attachPoints.ankle || { x: 0, y: 0 };
    positions.foot_left = {
      x: (positions.legs?.x || 0) + ankle.x - footAnkle.x,
      y: (positions.legs?.y || 0) + ankle.y - footAnkle.y,
    };
    positions.foot_left.mirror = true;
  }

  return positions;
}

/**
 * Wrap extracted SVG content in a positioned <g> element with a data-part attribute.
 */
function wrapPart(partName, svgRaw, x, y, extraAttrs = '') {
  const content = extractSVGContent(svgRaw);
  const mirrorTransform = partName.endsWith('_left') ? ' scale(-1, 1)' : '';
  return (
    `  <g data-part="${partName}" transform="translate(${x}, ${y})${mirrorTransform}"${extraAttrs}>` +
    `\n    ${content}\n  </g>`
  );
}

// ---------------------------------------------------------------------------
// Prop Assembly
// ---------------------------------------------------------------------------

/**
 * Assemble a prop SVG group.
 */
function assembleProp(propDef, projectDir) {
  const propId = propDef.id;
  const propPath = resolvePropPath(propId);
  if (!propPath) {
    // Try project-local props directory
    const localPath = path.join(projectDir, 'components', 'props', `${propId}.svg`);
    if (fs.existsSync(localPath)) {
      const svg = readSVG(localPath);
      return buildPropGroup(propId, propDef, svg);
    }
    return `<!-- WARNING: Prop "${propId}" not found -->`;
  }
  const svg = readSVG(propPath);
  return buildPropGroup(propId, propDef, svg);
}

function buildPropGroup(propId, propDef, svgContent) {
  const x = propDef.position?.x || 0;
  const y = propDef.position?.y || 0;
  const scale = propDef.scale || 1.0;
  const content = extractSVGContent(svgContent);
  return (
    `<g id="prop-${propId}" transform="translate(${x}, ${y}) scale(${scale})" opacity="0">\n` +
    `  ${content}\n` +
    `</g>`
  );
}

// ---------------------------------------------------------------------------
// Speech Bubble Assembly
// ---------------------------------------------------------------------------

/**
 * Generate speech bubble SVG groups.
 */
function assembleSpeechBubbles(bubbles, sceneDef, template) {
  if (!bubbles || bubbles.length === 0) return '';

  const parts = [];
  for (let i = 0; i < bubbles.length; i++) {
    const bubble = bubbles[i];
    const speakerPlacement = sceneDef.characters?.find(c => c.id === bubble.speaker);

    // Position bubble relative to speaker based on string enum
    const sx = speakerPlacement?.position?.x || 400;
    const sy = speakerPlacement?.position?.y || 400;
    let bx, by;
    switch (bubble.position) {
      case 'above':  bx = sx - 10; by = sy - 160; break;
      case 'left':   bx = sx - 120; by = sy - 80; break;
      case 'right':  bx = sx + 60; by = sy - 80; break;
      case 'auto':
      default:       bx = sx + 40; by = sy - 140; break;
    }

    const text = escapeXml(bubble.text || '');
    const fontSize = template.typography?.dialogueSize || 36;
    const fontFamily = template.typography?.dialogueFont || template.typography?.bodyFont || 'Caveat';
    const ink = template.palette?.ink || template.palette?.primary || '#1A1A1A';

    parts.push(
      `<g id="speech-${i}" transform="translate(${bx}, ${by})" opacity="0">`,
      `  <path d="M10,2 C30,0 50,0 70,2 C76,3 78,6 78,12 L78,32 C78,38 76,40 70,40 L28,40 L16,56 L22,40 L10,40 C4,40 2,38 2,32 L2,12 C2,6 4,3 10,2"`,
      `    stroke="${ink}" stroke-width="2.5" fill="none" stroke-linecap="round"/>`,
      `  <text class="bubble-text" x="40" y="26" text-anchor="middle" font-family="${fontFamily}" font-size="${fontSize * 0.6}" fill="${ink}" opacity="0">${text}</text>`,
      `</g>`
    );
  }
  return parts.join('\n');
}

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// ---------------------------------------------------------------------------
// GSAP Timeline Generation
// ---------------------------------------------------------------------------

/**
 * Generate the complete GSAP timeline script from the scene definition.
 *
 * @param {object} sceneDef   - Scene definition JSON
 * @param {object} template   - Merged template config
 * @returns {string}          JavaScript code for the <script> tag
 */
function generateTimeline(sceneDef, template) {
  const defaults = {
    ...template.animation,
    ...(template.canvas || {}),
  };

  const lines = [];

  // --------------- Init block: calculate and set stroke-dashoffset for draw-in ---------------
  lines.push(`
// ============================================================
// GSAP Timeline — Scene ${sceneDef.sceneId || '??'}
// Generated by the Stickman Animation Agent compositor
// ============================================================

gsap.registerPlugin();

// Init: calculate stroke-dashoffset for every path (draw-in setup)
document.querySelectorAll("svg path").forEach(function(path) {
  try {
    var len = path.getTotalLength();
    path.style.strokeDasharray = len;
    path.style.strokeDashoffset = len;
  } catch(e) { /* not a renderable path */ }
});

// Init: hide circles (used for eyes etc.) — they fade in during draw-in
document.querySelectorAll("svg circle").forEach(function(c) {
  c.style.opacity = "0";
});

var tl = gsap.timeline({ paused: true });
`);

  // --------------- Camera initial state ---------------
  if (sceneDef.camera?.initial) {
    const cam = sceneDef.camera.initial;
    lines.push(`// Camera initial state`);
    lines.push(`gsap.set(".camera-wrapper", { x: ${cam.x || 0}, y: ${cam.y || 0}, scale: ${cam.scale || 1.0}, transformOrigin: "center center" });`);
    lines.push('');
  }

  // --------------- Build sorted timeline events ---------------
  const events = [];

  // Character entrance events
  if (sceneDef.characters) {
    for (const char of sceneDef.characters) {
      if (char.enter) {
        events.push({
          time: char.enter.time || 0,
          target: char.id,
          action: `enter-${char.enter.method || 'draw-in'}`,
          duration: char.enter.duration,
          ...char.enter,
        });
      }
    }
  }

  // Prop entrance events
  if (sceneDef.props) {
    for (const prop of sceneDef.props) {
      if (prop.enter) {
        events.push({
          time: prop.enter.time || 0,
          target: `prop-${prop.id}`,
          action: prop.enter.method === 'draw-in' ? 'prop-draw-in' : `enter-${prop.enter.method || 'fade'}`,
          duration: prop.enter.duration,
          ...prop.enter,
          // Override target to keep the prop- prefix
          target: `prop-${prop.id}`,
        });
      }
    }
  }

  // Camera move events
  if (sceneDef.camera?.moves) {
    for (const move of sceneDef.camera.moves) {
      events.push({
        time: move.time,
        target: 'camera',
        action: `camera-${move.action || 'zoom'}`,
        duration: move.duration,
        scale: move.scale,
        x: move.x,
        y: move.y,
        focalTarget: move.target,
        intensity: move.intensity,
        ...move,
        // Ensure action has camera- prefix
        action: move.action?.startsWith('camera-') ? move.action : `camera-${move.action || 'zoom'}`,
      });
    }
  }

  // Speech bubble events
  if (sceneDef.speechBubbles) {
    for (let i = 0; i < sceneDef.speechBubbles.length; i++) {
      const sb = sceneDef.speechBubbles[i];
      events.push({
        time: sb.time || 0,
        target: `speech-${i}`,
        action: 'speech-bubble-in',
        duration: sb.duration || 2.0,
        bubbleIndex: i,
        holdDuration: sb.duration || 2.0,
      });
    }
  }

  // Explicit timeline events from the scene definition
  if (sceneDef.timeline) {
    for (const ev of sceneDef.timeline) {
      events.push(ev);
    }
  }

  // Sort by time
  events.sort((a, b) => (a.time || 0) - (b.time || 0));

  // --------------- Generate GSAP calls ---------------
  lines.push('// --- Timeline events ---');
  for (const event of events) {
    const code = generateAnimation(event, defaults);
    lines.push('');
    lines.push(code);
  }

  // --------------- Playback control ---------------
  lines.push('');
  lines.push('// Start playback');
  lines.push('tl.play();');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// SVG Defs — crosshatch patterns, etc.
// ---------------------------------------------------------------------------

function generateSVGDefs(template, characters) {
  const ink = template.palette?.ink || template.palette?.primary || '#1A1A1A';
  const inkLight = template.palette?.inkLight || template.palette?.secondary || '#4A4A4A';

  const defs = [];
  defs.push('<defs>');

  // Crosshatch pattern (used by t-shirt and other clothing)
  defs.push(`  <pattern id="crosshatch" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">`);
  defs.push(`    <line x1="0" y1="0" x2="0" y2="8" stroke="${inkLight}" stroke-width="0.8" opacity="0.3"/>`);
  defs.push(`  </pattern>`);

  // Diagonal lines pattern variant
  defs.push(`  <pattern id="diagonal-lines" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(30)">`);
  defs.push(`    <line x1="0" y1="0" x2="0" y2="6" stroke="${inkLight}" stroke-width="0.6" opacity="0.25"/>`);
  defs.push(`  </pattern>`);

  // Dots pattern
  defs.push(`  <pattern id="dots" width="10" height="10" patternUnits="userSpaceOnUse">`);
  defs.push(`    <circle cx="5" cy="5" r="1" fill="${inkLight}" opacity="0.2"/>`);
  defs.push(`  </pattern>`);

  // Per-character clothing patterns based on distinguishing features
  if (characters) {
    for (const char of characters) {
      if (char.distinguishing?.clothingPattern) {
        const patternId = `pattern-${char.id}`;
        const patternType = char.distinguishing.clothingPattern;
        if (patternType === 'crosshatch') {
          // Already defined above; create an alias reference
          defs.push(`  <!-- ${char.id} uses shared crosshatch pattern -->`);
        } else if (patternType === 'stripes') {
          defs.push(`  <pattern id="${patternId}" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(0)">`);
          defs.push(`    <line x1="0" y1="3" x2="6" y2="3" stroke="${inkLight}" stroke-width="0.8" opacity="0.3"/>`);
          defs.push(`  </pattern>`);
        } else if (patternType === 'dots') {
          defs.push(`  <!-- ${char.id} uses shared dots pattern -->`);
        }
      }
    }
  }

  defs.push('</defs>');
  return defs.join('\n');
}

// ---------------------------------------------------------------------------
// HTML Document Generation
// ---------------------------------------------------------------------------

/**
 * Build the complete HTML document.
 */
function buildHTML(sceneDef, template, characterSVGs, propSVGs, speechBubbleSVG, timelineScript, orientation) {
  const layout = orientation === 'vertical'
    ? (template.layout?.vertical || { width: 1080, height: 1920 })
    : (template.layout?.landscape || { width: 1920, height: 1080 });

  const width = layout.width || 1920;
  const height = layout.height || 1080;
  const bg = template.palette?.background || template.palette?.parchment || '#FFFFFF';
  const googleFonts = template.typography?.googleFontsImport || '';
  const gsapCdn = template.animation?.gsapCdn || 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js';
  const fps = template.rendering?.fps || template.canvas?.fps || 30;
  const sceneDuration = computeSceneDuration(sceneDef, template);

  // Generate defs for patterns
  const svgDefs = generateSVGDefs(template, sceneDef.characters?.map(c => ({
    ...c,
    distinguishing: c._sheetRef?.distinguishing,
  })));

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=${width}, height=${height}">
  <title>Scene ${sceneDef.sceneId || '??'}</title>
  ${googleFonts ? `<link rel="stylesheet" href="${googleFonts}">` : ''}
  <script src="${gsapCdn}"><\/script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      width: ${width}px;
      height: ${height}px;
      overflow: hidden;
      background: ${bg};
      font-family: '${template.typography?.bodyFont || 'sans-serif'}', cursive, sans-serif;
    }
    svg {
      display: block;
      width: ${width}px;
      height: ${height}px;
    }
    .bubble-text {
      font-family: '${template.typography?.dialogueFont || template.typography?.bodyFont || 'Caveat'}', cursive, sans-serif;
    }
  </style>
</head>
<body>
  <!-- HyperFrames metadata -->
  <div data-hyperframes-fps="${fps}" data-hyperframes-duration="${sceneDuration}" data-hyperframes-start="0" style="display:none"></div>

  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
    ${svgDefs}

    <!-- Background -->
    <rect width="${width}" height="${height}" fill="${bg}" />
    ${generateBackgroundDetails(sceneDef, template, width, height)}

    <!-- Camera wrapper — all scene content moves with this group -->
    <g class="camera-wrapper" transform-origin="center center">

      <!-- Props (behind characters) -->
      ${propSVGs}

      <!-- Characters -->
      ${characterSVGs}

      <!-- Speech bubbles -->
      ${speechBubbleSVG}

    </g>
  </svg>

  <script>
${timelineScript}
  <\/script>
</body>
</html>`;
}

/**
 * Generate subtle background details based on scene type and template.
 */
function generateBackgroundDetails(sceneDef, template, width, height) {
  const bg = sceneDef.background || template.palette?.background || '#FFFFFF';
  const lines = [];

  // For whiteboard template: add subtle parchment texture lines
  if (template.name === 'whiteboard') {
    const inkLight = template.palette?.inkLight || '#4A4A4A';
    // Subtle ruled lines
    for (let y = 200; y < height; y += 200) {
      lines.push(
        `    <line x1="80" y1="${y}" x2="${width - 80}" y2="${y}" ` +
        `stroke="${inkLight}" stroke-width="0.3" opacity="0.08" />`
      );
    }
  }

  return lines.join('\n');
}

/**
 * Compute total scene duration from the timeline events.
 * Takes the latest event time + its duration, plus a buffer.
 */
function computeSceneDuration(sceneDef, template) {
  let maxEnd = 0;
  const buffer = template.rendering?.durationBuffer || 0.5;

  // Check timeline events
  if (sceneDef.timeline) {
    for (const ev of sceneDef.timeline) {
      const end = (ev.time || 0) + (ev.duration || 1.0);
      if (end > maxEnd) maxEnd = end;
    }
  }

  // Check character entrances
  if (sceneDef.characters) {
    for (const c of sceneDef.characters) {
      if (c.enter) {
        const end = (c.enter.time || 0) + (c.enter.duration || 1.5);
        if (end > maxEnd) maxEnd = end;
      }
    }
  }

  // Check speech bubbles
  if (sceneDef.speechBubbles) {
    for (const sb of sceneDef.speechBubbles) {
      const end = (sb.time || 0) + (sb.duration || 2.0) + 0.5; // +0.5 for fade-out
      if (end > maxEnd) maxEnd = end;
    }
  }

  // Check camera moves
  if (sceneDef.camera?.moves) {
    for (const m of sceneDef.camera.moves) {
      const end = (m.time || 0) + (m.duration || 1.0);
      if (end > maxEnd) maxEnd = end;
    }
  }

  // Check prop entrances
  if (sceneDef.props) {
    for (const p of sceneDef.props) {
      if (p.enter) {
        const end = (p.enter.time || 0) + (p.enter.duration || 1.0);
        if (end > maxEnd) maxEnd = end;
      }
    }
  }

  return Math.ceil((maxEnd + buffer) * 10) / 10; // round up to 1 decimal
}

// ---------------------------------------------------------------------------
// Main composition function
// ---------------------------------------------------------------------------

/**
 * Compose a scene from its definition JSON into a complete HTML document.
 *
 * @param {string} sceneDefPath   - Path to the scene-definition.json file
 * @param {object} options
 * @param {string} options.projectDir   - Path to the project directory
 * @param {string} options.templateName - Template name (default: "whiteboard")
 * @param {string} options.outputPath   - Where to write the HTML file
 * @param {string} options.orientation  - "landscape" or "vertical" (default: "landscape")
 * @returns {object}  { outputPath, duration, characterCount, eventCount }
 */
export async function composeScene(sceneDefPath, options = {}) {
  const {
    projectDir,
    templateName = 'whiteboard',
    outputPath,
    orientation = 'landscape',
  } = options;

  // ---- Validate inputs ----
  if (!sceneDefPath) {
    throw new Error('sceneDefPath is required');
  }
  if (!projectDir) {
    throw new Error('options.projectDir is required');
  }

  const resolvedScenePath = path.resolve(sceneDefPath);
  const resolvedProjectDir = path.resolve(projectDir);

  // ---- Load scene definition ----
  console.log(`[compositor] Loading scene definition: ${resolvedScenePath}`);
  const sceneDef = readJSON(resolvedScenePath);

  if (!sceneDef.sceneId) {
    throw new Error(`Scene definition missing "sceneId" field: ${resolvedScenePath}`);
  }

  // ---- Load template ----
  console.log(`[compositor] Loading template: ${templateName}`);
  const template = loadTemplate(templateName);

  // ---- Load character sheets and assemble SVGs ----
  const characterSVGs = [];
  const charactersDir = path.join(resolvedProjectDir, 'characters');

  if (sceneDef.characters && sceneDef.characters.length > 0) {
    console.log(`[compositor] Assembling ${sceneDef.characters.length} character(s)...`);
    for (const charPlacement of sceneDef.characters) {
      const sheetPath = path.join(charactersDir, `${charPlacement.id}.json`);

      if (!fs.existsSync(sheetPath)) {
        console.warn(`[compositor] WARNING: Character sheet not found: ${sheetPath}`);
        characterSVGs.push(`<!-- WARNING: Character sheet "${charPlacement.id}" not found -->`);
        continue;
      }

      const charSheet = readJSON(sheetPath);
      // Attach sheet ref for pattern generation
      charPlacement._sheetRef = charSheet;
      const svg = assembleCharacter(charSheet, charPlacement, template);
      characterSVGs.push(svg);
      console.log(`[compositor]   - ${charSheet.id} (${charSheet.name || charSheet.id}): tier ${charSheet.tier || 1}, pose "${charPlacement.pose || 'standing'}"`);
    }
  }

  // ---- Assemble props ----
  const propSVGs = [];
  if (sceneDef.props && sceneDef.props.length > 0) {
    console.log(`[compositor] Assembling ${sceneDef.props.length} prop(s)...`);
    for (const propDef of sceneDef.props) {
      propSVGs.push(assembleProp(propDef, resolvedProjectDir));
      console.log(`[compositor]   - prop: ${propDef.id}`);
    }
  }

  // ---- Assemble speech bubbles ----
  const speechBubbleSVG = assembleSpeechBubbles(sceneDef.speechBubbles, sceneDef, template);

  // ---- Generate GSAP timeline ----
  console.log(`[compositor] Generating GSAP timeline...`);
  const timelineScript = generateTimeline(sceneDef, template);

  // Count total events for reporting
  let eventCount = (sceneDef.timeline?.length || 0);
  if (sceneDef.characters) eventCount += sceneDef.characters.filter(c => c.enter).length;
  if (sceneDef.props) eventCount += sceneDef.props.filter(p => p.enter).length;
  if (sceneDef.speechBubbles) eventCount += sceneDef.speechBubbles.length;
  if (sceneDef.camera?.moves) eventCount += sceneDef.camera.moves.length;

  // ---- Build HTML ----
  console.log(`[compositor] Building HTML document (${orientation})...`);
  const html = buildHTML(
    sceneDef,
    template,
    characterSVGs.join('\n      '),
    propSVGs.join('\n      '),
    speechBubbleSVG,
    timelineScript,
    orientation,
  );

  // ---- Write output ----
  const resolvedOutput = outputPath
    ? path.resolve(outputPath)
    : path.join(resolvedProjectDir, 'compositions', `scene-${sceneDef.sceneId}.html`);

  const outputDir = path.dirname(resolvedOutput);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(resolvedOutput, html, 'utf-8');

  const duration = computeSceneDuration(sceneDef, template);
  console.log(`[compositor] Wrote ${resolvedOutput}`);
  console.log(`[compositor] Duration: ${duration}s | Characters: ${sceneDef.characters?.length || 0} | Events: ${eventCount}`);

  return {
    outputPath: resolvedOutput,
    duration,
    characterCount: sceneDef.characters?.length || 0,
    eventCount,
  };
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

async function main() {
  const { values } = parseArgs({
    options: {
      scene: { type: 'string', short: 's' },
      project: { type: 'string', short: 'p' },
      template: { type: 'string', short: 't', default: 'whiteboard' },
      output: { type: 'string', short: 'o' },
      orientation: { type: 'string', default: 'landscape' },
      help: { type: 'boolean', short: 'h', default: false },
    },
    strict: true,
  });

  if (values.help || !values.scene || !values.project) {
    console.log(`
Stickman Animation Agent — Scene Compositor

Usage:
  node src/compositor/index.js \\
    --scene compositions/scene-01.json \\
    --project projects/my-video/ \\
    --template whiteboard \\
    --output compositions/scene-01.html

Options:
  --scene, -s        Path to scene definition JSON (required)
  --project, -p      Path to project directory (required)
  --template, -t     Template name (default: whiteboard)
  --output, -o       Output HTML path (default: project/compositions/scene-{id}.html)
  --orientation      "landscape" or "vertical" (default: landscape)
  --help, -h         Show this help message

Supported animation actions:
  ${supportedActions().join(', ')}
`);
    process.exit(values.help ? 0 : 1);
  }

  try {
    const result = await composeScene(values.scene, {
      projectDir: values.project,
      templateName: values.template,
      outputPath: values.output,
      orientation: values.orientation,
    });

    console.log(`\n[compositor] Done. Output: ${result.outputPath}`);
    process.exit(0);
  } catch (err) {
    console.error(`\n[compositor] ERROR: ${err.message}`);
    if (process.env.DEBUG) {
      console.error(err.stack);
    }
    process.exit(1);
  }
}

// Run CLI if this file is executed directly
const _argv1 = process.argv[1] || '';
if (import.meta.url === `file:///${_argv1.replace(/\\/g, '/')}` ||
    _argv1.endsWith('compositor/index.js') ||
    _argv1.endsWith('compositor\\index.js')) {
  main();
}

export default composeScene;
